### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by Tereseus** [iharmanpannu/jamming-app#2]
Nice job on already implementing the features you stated. Everything seems to work perfectly for both the search on enter and the alert to notify "playlist saved to spotify". The alert box definitely works, but if you wanted to spice up the way it looks you could make a small component above the Playlist which alerts the user that their playlist has been saved.

Either way good job, I also like the how you spaced out and indented your code, it makes it very easy to read.

**Comment by ihpannu** [comment]
Thank you is it ok if I use third party library it has really nice alert boxes. Thank you so much for reviewing my project and for excellent feedback.

**Comment by Tereseus** [comment]
You are welcome!
